FORMAT: 1A

# Bijli
Bijli API is a service which allows users to report electricity outages

# Group Bijli
Notes related resources of the **Bijli API**

## Session [/startSession]

This is used to start a session and assign a unique id to each user 

+ Response 200 (application/json )
    {
        "user_id":"23425245234sflgkg"
    }

## Bijli Collection [/notes]

### Create a Electricity Report [POST]

Data about user being created. With following attributes are:

    + `isBijli` ... Set to false if there is an outage
    + `Location` (optional) ... age of the user
+ Request (application/json)

        { 
            "isBijli": true,
            "Location": {
                "coordinate":{
                    "latitude": -78.75,
                    "longitude": 20.4
                },
                "areaCode":"388001"
            }
            
        }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve an Outage [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
